{% set name = "patchnetvlad" %}
{% set version = "0.1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/patchnetvlad-{{ version }}.tar.gz
  sha256: d55614c89ecaa28fba5a52c866517a49c6c1aa4479af1856c5a43eb0c4ae3d47

build:
  number: 1
  noarch: python
  entry_points:
    - patchnetvlad-match-two=match_two:main
    - patchnetvlad-feature-match=feature_match:main
    - patchnetvlad-feature-extract=feature_extract:main
    - patchnetvlad-download-models=download_models:download_all_models
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - tqdm
    - matplotlib-base
    - opencv
    - scikit-learn
    - natsort
    - pillow
    - pytorch
    - torchvision
    - faiss

test:
  imports:
    - patchnetvlad
    - patchnetvlad.models
    - patchnetvlad.tools
  commands:
    - pip check
    - patchnetvlad-match-two --help
    - patchnetvlad-feature-match --help
    - patchnetvlad-feature-extract --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/QVPR/Patch-NetVLAD
  summary: 'Patch-NetVLAD: An open-source Python implementation of the CVPR2021 paper'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
