{% set name = "patchnetvlad" %}
{% set version = "0.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/patchnetvlad-{{ version }}.tar.gz
  sha256: 2e9d8c390327a2f276f40e8f20aecd865cfad9ac060e79540320c13a8b26a3e5

build:
  number: 0
  noarch: python
  entry_points:
    - patchnetvlad-match-two=match_two:main
    - patchnetvlad-feature-match=feature_match:main
    - patchnetvlad-feature-extract=feature_extract:main
    - patchnetvlad-download-models=download_models:download_all_models
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - scipy
    - tqdm
    - matplotlib-base
    - opencv
    - scikit-learn
    - natsort
    - pillow
    - pytorch
    - torchvision
    - faiss

test:
  imports:
    - patchnetvlad
    - patchnetvlad.models
    - patchnetvlad.tools
  commands:
    - pip check
    - patchnetvlad-match-two --help
    - patchnetvlad-feature-match --help
    - patchnetvlad-feature-extract --help
  requires:
    - pip

about:
  home: https://github.com/QVPR/Patch-NetVLAD
  summary: 'Patch-NetVLAD: An open-source Python implementation of the CVPR2021 paper'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
